 const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_CART : 'ADD_CART',
    CLEAR_OUT : "CLEAR_OUT",
    REMOVE_ITEM : 'REMOVE_ITEM',
    CLEAR_CART : "CLEAR_CART",
    SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
    UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE'
  };
  
  export default CartActionTypes;
  